version: '3.4'

services:
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    env_file: 'env.dev'
    ports: 
      - 3306:3306

  gatewayservice:
    image: pythonfinalproject2021.azurecr.io/gatewayservice
    container_name: gatewayservice
    build: ../gateway_service
    domainname: "diamonds"
    ports:
      - 5001:5001
    env_file: 'env.dev'
    depends_on: 
      - dataservice
  
  dataservice:
    image: pythonfinalproject2021.azurecr.io/dataservice
    container_name: dataservice
    build: ../data_service
    ports:
      - 5002:5002
    env_file: 'env.dev'
    depends_on: 
      - db

volumes:
  db-data:
    # driver: azure_file
    # driver_opts:
    #   share_name: myfileshare
    #   storage_account_name: finalproject2021storage