version: '3.4'

services:
  db:
    image: mysql:5.7.35
    volumes:
      - db-data:/var/lib/mysql
    env_file: 'env.dev'
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
    ports: 
      - 3306:3306

  gatewayservice:
    image: mydiamonds.azurecr.io/gatewayservice
    container_name: gatewayservice
    build: ../gateway_service
    domainname: "diamondsproject"
    ports:
      - 5001:5001
    env_file: 'env.dev'
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
    depends_on: 
      - alertservice
      - dataservice
      - fitservice
  
  dataservice:
    image: mydiamonds.azurecr.io/dataservice
    container_name: dataservice
    build: ../data_service
    ports:
      - 5002:5002
    env_file: 'env.dev'
    deploy:
      restart_policy:
        condition: on-failure  
      resources:
        limits:
          cpus: '0.5'
    depends_on: 
      - db
      - alertservice

  alertservice:
    image: mydiamonds.azurecr.io/alertservice
    container_name: alertservice
    build: ../alerts_service
    ports:
      - 5005:5005
    env_file: 'env.dev'
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
    
  fitservice:
    image: mydiamonds.azurecr.io/fitservice
    container_name: fitservice
    build: ../fit_service
    volumes: 
      - fitdirectory:/app/files
    ports:
      - 5004:5004
    env_file: 'env.dev'    
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'  
    depends_on: 
      - alertservice
      - dataservice


volumes:
  fitdirectory:
    driver: azure_file
    driver_opts:
      share_name: modelfileshare
      storage_account_name: diamondsstorage
  db-data:
    driver: azure_file
    driver_opts:
      share_name: myfileshare
      storage_account_name: diamondsstorage