version: '3.4'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootdiamonds
      MYSQL_DATABASE: diamonds
      MYSQL_USER: diamonds
      MYSQL_PASSWORD: diamonds
    ports: 
      - 3306:3306

  gatewayservice:
    image: pythonfinalproject2021.azurecr.io/gatewayservice
    container_name: gatewayservice
    build: ../gateway_service
    ports:
      - 5001:5001
    env_file: 'env.dev'
    depends_on: 
      - dataservice
  
  dataservice:
    image: pythonfinalproject2021.azurecr.io/dataservice
    container_name: dataservice
    build: ../data_service
    ports:
      - 5002:5002
    env_file: 'env.dev'
    depends_on: 
      - db

volumes:
  db_data:
    