version: '3.4'

services:
  gatewayservice:
    image: pythonfinalproject2021.azurecr.io/gatewayservice
    container_name: gatewayservice
    build: ../gateway_service
    ports:
      - 5001:5001
    env_file: 'env.dev'
  
  dataservice:
    image: pythonfinalproject2021.azurecr.io/dataservice
    container_name: dataservice
    build: ../data_service
    ports:
      - 5002:5002
    env_file: 'env.dev'
    